version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: polstack-postgres
    environment:
      POSTGRES_USER: postgreslocal
      POSTGRES_PASSWORD: postgreslocal
      POSTGRES_DB: polstack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    env_file: ".env"
    networks:
      - minio_network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/export
      - minio_data:/root/.minio
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    command: server /export --console-address :9001

  createbuckets:
    image: minio/mc
    env_file: ".env"
    depends_on:
      - minio
    networks:
      - minio_network
    environment:
      - BUCKET_NAME=${S3_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc 
      /usr/bin/mc config host add myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      /usr/bin/mc mb myminio/${S3_BUCKET_NAME};
      /usr/bin/mc policy download myminio/${S3_BUCKET_NAME}"

volumes:
  postgres_data:
  minio_data:

networks:
  minio_network:
    driver: bridge
